// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PCSite.Models;

#nullable disable

namespace PCSite.Migrations
{
    [DbContext(typeof(SatisdbContext))]
    [Migration("20240731140406_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PCSite.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Adres")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Bakiye")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("KayitTarihi")
                        .HasColumnType("datetime");

                    b.Property<int>("KullaniciTipi")
                        .HasColumnType("int");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("TelefonNumarasi")
                        .HasMaxLength(15)
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Email" }, "Email")
                        .IsUnique();

                    b.ToTable("kullanici", (string)null);
                });

            modelBuilder.Entity("PCSite.Models.Satis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<sbyte?>("KargoDurumu")
                        .HasColumnType("tinyint");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<sbyte?>("OdemeDurumu")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("SatisTarihi")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("ToplamFiyat")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "KullaniciId" }, "KullaniciId");

                    b.ToTable("satis", (string)null);
                });

            modelBuilder.Entity("PCSite.Models.Satisdetay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("BirimFiyat")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("Miktar")
                        .HasColumnType("int");

                    b.Property<int?>("SatisId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ToplamFiyat")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("UrunId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SatisId" }, "SatisId");

                    b.HasIndex(new[] { "UrunId" }, "UrunId");

                    b.ToTable("satisdetay", (string)null);
                });

            modelBuilder.Entity("PCSite.Models.Sepet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "KullaniciId" }, "KullaniciId")
                        .HasDatabaseName("KullaniciId1");

                    b.ToTable("sepet", (string)null);
                });

            modelBuilder.Entity("PCSite.Models.Sepeturun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Miktar")
                        .HasColumnType("int");

                    b.Property<int?>("SepetId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ToplamFiyat")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("UrunId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SepetId" }, "SepetId");

                    b.HasIndex(new[] { "UrunId" }, "UrunId")
                        .HasDatabaseName("UrunId1");

                    b.ToTable("sepeturun", (string)null);
                });

            modelBuilder.Entity("PCSite.Models.Urun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Fiyat")
                        .HasColumnType("float");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime");

                    b.Property<string>("Kategori")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("OlusturmaTarihi")
                        .HasColumnType("datetime");

                    b.Property<int>("StokMiktari")
                        .HasColumnType("int");

                    b.Property<string>("UrunAdi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("urun", (string)null);
                });

            modelBuilder.Entity("PCSite.Models.Urundetay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Anakart")
                        .HasColumnType("longtext");

                    b.Property<string>("Depolama")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("EkranBoyutu")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("EkranCozunurlugu")
                        .HasColumnType("longtext");

                    b.Property<string>("EkranKartı")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("EkranYenilemeHizi")
                        .HasColumnType("int");

                    b.Property<string>("Islemci")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("KlavyeBoyutu")
                        .HasColumnType("int");

                    b.Property<string>("KlavyeTuru")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Ram")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("RAM");

                    b.Property<int?>("UrunId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UrunId" }, "UrunId")
                        .HasDatabaseName("UrunId2");

                    b.ToTable("urundetay", (string)null);
                });

            modelBuilder.Entity("PCSite.Models.Satis", b =>
                {
                    b.HasOne("PCSite.Models.Kullanici", "Kullanici")
                        .WithMany("Satis")
                        .HasForeignKey("KullaniciId")
                        .HasConstraintName("satis_ibfk_1");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("PCSite.Models.Satisdetay", b =>
                {
                    b.HasOne("PCSite.Models.Satis", "Satis")
                        .WithMany("Satisdetays")
                        .HasForeignKey("SatisId")
                        .HasConstraintName("satisdetay_ibfk_1");

                    b.HasOne("PCSite.Models.Urun", "Urun")
                        .WithMany("Satisdetays")
                        .HasForeignKey("UrunId")
                        .HasConstraintName("satisdetay_ibfk_2");

                    b.Navigation("Satis");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("PCSite.Models.Sepet", b =>
                {
                    b.HasOne("PCSite.Models.Kullanici", "Kullanici")
                        .WithMany("Sepets")
                        .HasForeignKey("KullaniciId")
                        .HasConstraintName("sepet_ibfk_1");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("PCSite.Models.Sepeturun", b =>
                {
                    b.HasOne("PCSite.Models.Sepet", "Sepet")
                        .WithMany("Sepeturuns")
                        .HasForeignKey("SepetId")
                        .HasConstraintName("sepeturun_ibfk_1");

                    b.HasOne("PCSite.Models.Urun", "Urun")
                        .WithMany("Sepeturuns")
                        .HasForeignKey("UrunId")
                        .HasConstraintName("sepeturun_ibfk_2");

                    b.Navigation("Sepet");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("PCSite.Models.Urundetay", b =>
                {
                    b.HasOne("PCSite.Models.Urun", "Urun")
                        .WithMany("Urundetays")
                        .HasForeignKey("UrunId")
                        .HasConstraintName("urundetay_ibfk_1");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("PCSite.Models.Kullanici", b =>
                {
                    b.Navigation("Satis");

                    b.Navigation("Sepets");
                });

            modelBuilder.Entity("PCSite.Models.Satis", b =>
                {
                    b.Navigation("Satisdetays");
                });

            modelBuilder.Entity("PCSite.Models.Sepet", b =>
                {
                    b.Navigation("Sepeturuns");
                });

            modelBuilder.Entity("PCSite.Models.Urun", b =>
                {
                    b.Navigation("Satisdetays");

                    b.Navigation("Sepeturuns");

                    b.Navigation("Urundetays");
                });
#pragma warning restore 612, 618
        }
    }
}
